"""empty message

Revision ID: 940702efad28
Revises: 01184206d697
Create Date: 2022-06-20 19:12:14.131550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940702efad28'
down_revision = '01184206d697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('status', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'status')
    # ### end Alembic commands ###
