"""empty message

Revision ID: bf854506715c
Revises: 940702efad28
Create Date: 2022-06-21 15:18:59.060173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf854506715c'
down_revision = '940702efad28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('loan', sa.Column('time_last_payment', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payment', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'time_created')
    op.drop_column('loan', 'time_last_payment')
    op.drop_column('loan', 'time_created')
    # ### end Alembic commands ###
